### ISSUE TITLE
missing calculate_average_height function

### ISSUE THREAD

**Issue by Murkyy** [MertcanErdem/LasBuildSeg#1]
hello, thanks for your work !

Could you please provide the source code of the calculate_average_height function ?

It seems to be in the pypi package but not in the source code.

`def calculate_average_height(geojson_file, height_data,height_profile):
    gdf = gpd.read_file(geojson_file)
    avg_heights = []
    for index, row in gdf.iterrows():
        polygon = row['geometry']
        polygon_heights = []
        for point in polygon.exterior.coords:
            # Extract height from height data at the coordinate location
            x, y = point[0], point[1]
            height = height_data[int((y - height_profile['transform'][5]) / abs(height_profile['transform'][4]))][int((x - height_profile['transform'][2]) / height_profile['transform'][0])]
            polygon_heights.append(height)
        # Calculate average height for the polygon
        avg_height = np.mean(polygon_heights)
        avg_heights.append(avg_height)
    # Add average height to GeoDataFrame
    gdf['average_height'] = avg_heights
    return gdf`

**Comment by MertcanErdem** [comment]
Updated the source code to include calculate_average_height function
